export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

//Because this is a promise it has three states
export const REQUEST_CHARACTERS_PENDING  = 'REQUEST_CHARACTERS_PENDING';
export const REQUEST_CHARACTERS_SUCCESS  = 'REQUEST_CHARACTERS_SUCCESS';
export const REQUEST_CHARACTERS_FAILED  = 'REQUEST_CHARACTERS_FAILED';
